FROM node:22

WORKDIR /app

# Сначала только package*.json — это best practice
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Теперь копируем всё остальное
COPY . .

# Собираем билд
RUN npm run build

# Запускаем уже собранный JS
CMD ["node", "dist/apps/api-gateway/src/main.js"]
